version: '3'

volumes: 
  graphdb:
    driver: local
  
services:

  graphdb:
    image: pcharoen/graphdb:9.0.0-free
    restart: always
    volumes:
      - graphdb:/opt
    ports:
      - "7200:7200"
