version: '3'

volumes: 
  data:
    driver: local
  web:
    driver: local
  
services:

  web:
    image: pcharoen/graphdb:9.0.0-free
    restart: always
    volumes:
      - data:/opt
      - "/opt/graphdb/home/import:/opt/graphdb/home/import"
    ports:
      - "7200:7200"
